host_address:
  value: "192.168.1.5"
  dtype: string

buffer_size:
  value: 3
  dtype: int

use_object:
  value: true
  dtype: bool

offset:
  robot:
    z:
      value: -0.1
      dtype: double
  object:
    z:
      value: -0.225
      dtype: double